---
version: '3'
services:
  freqtrade-backtest:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: unless-stopped
    container_name: freqtrade-backtest
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./keras_models:/freqtrade/user_data/strategies/models"
    command: >
     download-data
        --timerange=12012023-12012024
        --logfile /freqtrade/user_data/logs/freqtrade-download.log
        --config /freqtrade/config.json
        --trading-mode futures
        -t 5m
        -p 
