---
version: '3'
services:
  freqtrade-download:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-download
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
     download-data
        --days 2
        --logfile /freqtrade/user_data/logs/freqtrade-download.log
        --config /freqtrade/config.json
        --dl-trades
        -t 5m
        -p ADA/EUR XRP/EUR DOT/EUR AVAX/EUR SUI/EUR MATIC/EUR ARB/EUR SEI/EUR ETC/EUR ATOM/EUR ENS/EUR KAVA/EUR LINK/EUR INJ/EUR NEAR/EUR DOGE/EUR XTZ/EUR SC/EUR STX/EUR LDO/EUR TIA/EUR OP/EUR MINA/EUR FIL/EUR FET/EUR SNX/EUR ALGO/EUR DAI/EUR KSM/EUR GRT/EUR BLUR/EUR