---
services:
  freqtrade-convert-trades:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-convert-trades
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
     trades-to-ohlcv 
        --exchange kraken 
        --config /freqtrade/config.json
        --userdir /freqtrade/user_data/
        -t 5m
    networks:
      - freqtrade-network-convert-trades

networks:
  freqtrade-network-convert-trades: