---
version: '3'
services:
  freqtrade:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNPredict:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./keras_models:/freqtrade/user_data/strategies/models"
    command: >
      trade
        --logfile /freqtrade/user_data/logs/freqtrade.log
        --db-url sqlite:////freqtrade/user_data/databases/tradesv3.sqlite
        --config /freqtrade/config.json
        --freqaimodel CatboostRegressor
        --strategy NNPredict_CNN
