---
version: '3'
services:
  freqtrade-hyperopt:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-hyperopt
    volumes:
      - "./config_backtest.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
      hyperopt 
        --timerange=20231228-
        --strategy NNTC
        --logfile /freqtrade/user_data/logs/freqtrade-hyperopt.log
        --config /freqtrade/config.json
        --freqaimodel CatboostRegressor
        --spaces roi trailing stoploss sell 
        --hyperopt-loss ProfitDrawDownHyperOptLoss
        --epochs 100
        --min-trades 1
    networks:
      - freqtrade-network-hyperopt

networks:
  freqtrade-network-hyperopt:
