---
version: '3'
services:
  freqtrade-download:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-download
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
     download-data
        --days 1000
        --logfile /freqtrade/user_data/logs/freqtrade-download.log
        --config /freqtrade/config.json
        --dl-trades
        -t 5m
        -p ADA/EUR LINK/EUR TIA/EUR DOGE/EUR XRP/EUR XTZ/EUR SC/EUR DOT/EUR MATIC/EUR ARB/EUR SUI/EUR SEI/EUR DYDX/EUR TRX/EUR ATOM/EUR ICP/EUR APT/EUR KAVA/EUR PYTH/EUR STX/EUR FIL/EUR PERP/EUR WOO/EUR LUNC/EUR JTO/EUR FET/EUR MINA/EUR GRT/EUR
    networks:
      - freqtrade-network-download

networks:
  freqtrade-network-download: