---
version: '3'
services:
  freqtrade:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: unless-stopped
    container_name: freqtrade-trade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNPredict:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./models:/freqtrade/user_data/strategies/models"
    ports:
      - "0.0.0.0:9671:9671"
