ARG sourceimage=freqtradeorg/freqtrade
ARG sourcetag=develop_freqai
FROM ${sourceimage}:${sourcetag}

COPY ./freqtrade-git/requirements-freqai.txt ./freqtrade-git/requirements-freqai-rl.txt /freqtrade/

RUN pip install -r requirements-freqai-rl.txt --user 

USER ftuser

RUN pip install --user tensorflow

RUN pip install --user PyWavelets darts multiprocess finta statsforecast prettytable

RUN pip uninstall -y polars
