---
services:
  freqtrade-download:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-download
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
     download-data
        --days 1200
        -t 5m
        --logfile /freqtrade/user_data/logs/freqtrade-download.log
        --userdir /freqtrade/user_data/
        --config /freqtrade/config.json
        --dl-trades
    networks:
      - freqtrade-network-download

networks:
  freqtrade-network-download:
