---
version: '3'
services:
  freqtrade-backtest:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-backtest
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
     test-pairlist
        --config /freqtrade/config.json
    networks:
      - freqtrade-network-test-pairlist

networks:
  freqtrade-network-test-pairlist: