---
services:
  freqtrade-csv-convert:
    image: "blastbeng/freqtrade:freqai"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: "no"
    container_name: freqtrade-csv-convert
    volumes:
      - "./config.json:/freqtrade/config.json"
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNTC:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./generated_models:/freqtrade/user_data/strategies/models"
    command: >
     convert-trade-data 
      --exchange kraken
      --format-from kraken_csv 
      --format-to feather
    networks:
      - freqtrade-network-csv-convert

networks:
  freqtrade-network-csv-convert: