---
version: '3'
services:
  freqtrade-trade:
    image: "blastbeng/freqtrade:freqai"
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: "./Dockerfile"
    restart: unless-stopped
    container_name: freqtrade-trade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./phils_strategies/NNPredict:/freqtrade/user_data/strategies"
      - "./phils_strategies/utils:/freqtrade/user_data/strategies/utils"
      - "./models:/freqtrade/user_data/strategies/models"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freq  trade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "0.0.0.0:9671:9671"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/databases/tradesv3.sqlite
      --config /freqtrade/user_data/configs/config.json
      --freqaimodel CatboostRegressor
      --strategy NNPredict_LSTM2
